spring:
  config:
    activate:
      on-profile: test
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    driver-class-name: org.h2.Driver
    username: root
    password:
    url: jdbc:h2:~/testdb
logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace

openbank:
  useCode : ""
  client-id: ""
  client-secret: ""
  redirect-url: ""
  cntr-account: ""